title: "Ag Econ Paper Picnic 🧺"
email: "cai.yetian@ufl.edu"
author: "Yetian Cai"
description: "A weekly basket with the latest published research in Agricultural Economics."
baseurl: ""
url: "https://caiyetiana.github.io/ag_econ_picnic/"
github_username: "caiyetiana"
exclude: 
  - "Gemfile"
  - "Gemfile.lock"
  - credentials.R
