name: Test Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests

    - name: Run a simple script
      run: |
        echo "Hello, GitHub Actions!"
        python -m pytest

    - name: Run another command
      run: |
        echo "The current directory is:"
        pwd
        echo "List of files in the directory:"
        ls -la
